server:
   port: 9888
es:
   port: 9200
   host: 47.115.34.118
   scheme: http
spring:
   datasource:
      hikari:
         master:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/famiao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
            username: root
            password: ntVklfM5@VMj2pHd
         slave:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://47.115.34.118:3306/famiao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
            username: root
            password: ntVklfM5@VMj2pHd
logging:
   level:
      com.famiao.search: debug
dynamic:
   sql:
      path: D:\Env\project\fm-search\src\main\resources\template\DynamicSqlTemplete.xml
   cron:
      expression: 0 0 0/1 * * ?